// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_ryVWajf7zZZtYxR0_YvtPq2Q3YRNuQ',
    appId: '1:802920906172:web:2d2505b8ea35c92b7cffb9',
    messagingSenderId: '802920906172',
    projectId: 'komyuniti-9b5b4',
    authDomain: 'komyuniti-9b5b4.firebaseapp.com',
    storageBucket: 'komyuniti-9b5b4.appspot.com',
    measurementId: 'G-5SJL982GF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8DXHo1MhGzyPzXNVbVuo6En53rrMQN8k',
    appId: '1:802920906172:android:deb75220d43d17237cffb9',
    messagingSenderId: '802920906172',
    projectId: 'komyuniti-9b5b4',
    storageBucket: 'komyuniti-9b5b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzwpK-vdLsBfXO2bXR5U7KnkNxpqlFfMs',
    appId: '1:802920906172:ios:5359ce1dc8683c307cffb9',
    messagingSenderId: '802920906172',
    projectId: 'komyuniti-9b5b4',
    storageBucket: 'komyuniti-9b5b4.appspot.com',
    iosClientId: '802920906172-qo6cns5r2eqess5ke993pkm4ihrnuh4s.apps.googleusercontent.com',
    iosBundleId: 'com.kiishidart.komyuniti',
  );
}
